In [1]:
import uproot
import pandas as pd

In [4]:
with uproot.open("/home/silver/PTPSim/output.root") as file:
    print("Structure complète :", file.classnames())

Structure complète : {'status;2': 'RAT::ObjInt', 'status;1': 'RAT::ObjInt', 'T;1': 'TTree', 'runT;1': 'TTree', 'log;1': 'TObjString', 'macro;1': 'TObjString', 'ratdb;1': 'TObjString', 'obj;1': 'TDirectory'}

In [9]:
df.head(2)

,fUniqueID,fBits,id,type,startTime.fSec,startTime.fNanoSec,nestedtubeinfo.fUniqueID,nestedtubeinfo.fBits,nestedtubeinfo.pos,nestedtubeinfo.dir,...,ch_status.lcns,ch_status.online,ch_status.cable_offset,ch_status.charge_scale,ch_status.pulse_width_scale,ch_status.default_offset,ch_status.default_is_online,ch_status.ChargeScaleIndex,ch_status.default_charge_scale,ch_status.default_pulse_width_scale
0,0,0,1,0,1790070907,659652000,[0],[0],[()],[()],...,[-1],[1],[60.0],[1.0],[1.0],60.0,1,,1.0,1.0

In [15]:
with uproot.open("/home/silver/PTPSim/output.root") as file:
    # 1. Parcourir tous les objets du fichier ROOT
    for key, classname in file.classnames().items():
        
        # 2. Vérifier si l'objet est un TTree
        if classname == "TTree":
            # Nettoyer le nom de la clé (enlever le numéro de cycle comme ';1')
            tree_name = key.split(";")[0]
            
            print(f"\n===== Branches de l'arbre : {tree_name} =====")
            
            # 3. Récupérer l'arbre et lister ses branches
            tree = file[key]
            branches = tree.keys()
            if branches:
                for branch in branches:
                    print(f"  -> {branch}")
            else:
                print("  (Aucune branche trouvée)")
            tree = file["runT"]
            df = tree.arrays(library="pd")

===== Branches de l'arbre : T =====
  -> ds
  -> ds/TObject
  -> ds/TObject/fUniqueID
  -> ds/TObject/fBits
  -> ds/runID
  -> ds/ratVersion
  -> ds/procResult
  -> ds/procResult/procResult.first
  -> ds/procResult/procResult.second
  -> ds/mc
  -> ds/mc/mc.fUniqueID
  -> ds/mc/mc.fBits
  -> ds/mc/mc.id
  -> ds/mc/mc.numPE
  -> ds/mc/mc.numDarkHits
  -> ds/mc/mc.utc.fSec
  -> ds/mc/mc.utc.fNanoSec
  -> ds/mc/mc.summary
  -> ds/mc/mc.particle
  -> ds/mc/mc.parent
  -> ds/mc/mc.track
  -> ds/mc/mc.pmt
  -> ds/mc/mc.nt
  -> ds/calib
  -> ds/calib/calib.fUniqueID
  -> ds/calib/calib.fBits
  -> ds/calib/calib.id
  -> ds/calib/calib.mode
  -> ds/calib/calib.intensity
  -> ds/calib/calib.wavelength
  -> ds/calib/calib.name
  -> ds/calib/calib.utc.fSec
  -> ds/calib/calib.utc.fNanoSec
  -> ds/calib/calib.pos
  -> ds/calib/calib.dir
  -> ds/ev
  -> ds/ev/ev.fUniqueID
  -> ds/ev/ev.fBits
  -> ds/ev/ev.id
  -> ds/ev/ev.qTotal
  -> ds/ev/ev.calibratedTriggerTime
  -> ds/ev/ev.deltat
  -> ds/ev/ev.utc.fSec
  -> ds/ev/ev.utc.fNanoSec
  -> ds/ev/ev.trigger_word
  -> ds/ev/ev.pmt
  -> ds/ev/ev.digitpmt
  -> ds/ev/ev.lappd
  -> ds/ev/ev.fitResults
  -> ds/ev/ev.classifierResults
  -> ds/ev/ev.digitizer
  -> ds/ev/ev.eventCleaningWord
  -> ds/ev/ev.triggerPeak

===== Branches de l'arbre : runT =====
  -> run
  -> run/TObject
  -> run/TObject/fUniqueID
  -> run/TObject/fBits
  -> run/id
  -> run/type
  -> run/startTime
  -> run/startTime/startTime.fSec
  -> run/startTime/startTime.fNanoSec
  -> run/nestedtubeinfo
  -> run/nestedtubeinfo/nestedtubeinfo.fUniqueID
  -> run/nestedtubeinfo/nestedtubeinfo.fBits
  -> run/nestedtubeinfo/nestedtubeinfo.pos
  -> run/nestedtubeinfo/nestedtubeinfo.dir
  -> run/nestedtubeinfo/nestedtubeinfo.length
  -> run/nestedtubeinfo/nestedtubeinfo.core_r
  -> run/nestedtubeinfo/nestedtubeinfo.inner_r
  -> run/nestedtubeinfo/nestedtubeinfo.outer_r
  -> run/nestedtubeinfo/nestedtubeinfo.core_material
  -> run/nestedtubeinfo/nestedtubeinfo.inner_material
  -> run/nestedtubeinfo/nestedtubeinfo.outer_material
  -> run/pmtinfo
  -> run/pmtinfo/pmtinfo.fUniqueID
  -> run/pmtinfo/pmtinfo.fBits
  -> run/pmtinfo/pmtinfo.pos
  -> run/pmtinfo/pmtinfo.dir
  -> run/pmtinfo/pmtinfo.type
  -> run/pmtinfo/pmtinfo.channel_num
  -> run/pmtinfo/pmtinfo.modeltype
  -> run/pmtinfo/pmtinfo.models
  -> run/pmtinfo/pmtinfo.individual_efficiency_corr
  -> run/pmtinfo/pmtinfo.individual_noise_rate
  -> run/pmtinfo/pmtinfo.individual_afterpulse_fraction
  -> run/ch_status
  -> run/ch_status/ch_status.TObject
  -> run/ch_status/ch_status.TObject/ch_status.fUniqueID
  -> run/ch_status/ch_status.TObject/ch_status.fBits
  -> run/ch_status/ch_status.lcn_to_index
  -> run/ch_status/ch_status.lcn_to_index/ch_status.lcn_to_index.first
  -> run/ch_status/ch_status.lcn_to_index/ch_status.lcn_to_index.second
  -> run/ch_status/ch_status.pmtid_to_index
  -> run/ch_status/ch_status.pmtid_to_index/ch_status.pmtid_to_index.first
  -> run/ch_status/ch_status.pmtid_to_index/ch_status.pmtid_to_index.second
  -> run/ch_status/ch_status.lcns
  -> run/ch_status/ch_status.online
  -> run/ch_status/ch_status.cable_offset
  -> run/ch_status/ch_status.charge_scale
  -> run/ch_status/ch_status.pulse_width_scale
  -> run/ch_status/ch_status.default_offset
  -> run/ch_status/ch_status.default_is_online
  -> run/ch_status/ch_status.ChargeScaleIndex
  -> run/ch_status/ch_status.default_charge_scale
  -> run/ch_status/ch_status.default_pulse_width_scale

In [16]:
df.head()

,fUniqueID,fBits,id,type,startTime.fSec,startTime.fNanoSec,nestedtubeinfo.fUniqueID,nestedtubeinfo.fBits,nestedtubeinfo.pos,nestedtubeinfo.dir,...,ch_status.lcns,ch_status.online,ch_status.cable_offset,ch_status.charge_scale,ch_status.pulse_width_scale,ch_status.default_offset,ch_status.default_is_online,ch_status.ChargeScaleIndex,ch_status.default_charge_scale,ch_status.default_pulse_width_scale
0,0,0,1,0,1790070907,659652000,[0],[0],[()],[()],...,[-1],[1],[60.0],[1.0],[1.0],60.0,1,,1.0,1.0